=pod

=encoding UTF-8

=head1 NAME

Alien::ZMQ::latest - Alien package for the ZeroMQ library

=head1 VERSION

version 0.004_01

=head1 DESCRIPTION

Installs the latest release of ZeroMQ.

You can use environment variable to specify ZeroMQ version to be installed.
Following example can build latest ZeroMQ of version 3.x.
(Windows and Strawberry perl is intented here)

    > set ALIEN_ZMQ_wVERSION=3.*
    > perl Makefile.PL
    > gmake
    > gmake install

=head1 SEE ALSO

L<ZeroMQ|http://zeromq.org/>

=head1 AUTHOR

Zakariyya Mughal <zmughal@cpan.org>, (Capability to set version is added by toshifjw@cpan.org)

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2017 by Zakariyya Mughal.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
